"""Independent exact coverage and dual replay, Python standard library only.
Planar profiles are generated by a direct Cartesian product, not the discovery
program's recursion. Shape membership uses direct coordinate-plane tests.
"""
from itertools import product
from fractions import Fraction
from pathlib import Path
import json

HERE=Path(__file__).resolve().parent

def all_profiles(R,plane):
 out=[]
 for row in product(*(range(R-i+2) for i in range(R+1))):
  if any(row[i]<row[i+1] for i in range(R)):continue
  if row[2 if plane=='xy' else 1]<2:continue
  extent=sum(x>0 for x in row)
  drops=[i for i in range(1,extent) if row[i]<row[i-1]]
  if len(drops)>2:continue
  if plane=='xy' and sum(i>=2 for i in drops)>1:continue
  out.append((row,extent,row[0]))
 return out

def shapes(R):
 xy=all_profiles(R,'xy');yz=all_profiles(R,'yz')
 grid=tuple(product(range(R+1),repeat=3))
 for A,B,C in product(xy,xy,yz):
  if A[1]!=B[1] or A[2]!=C[1] or B[2]!=C[2]:continue
  rows=(A[0],B[0],C[0])
  T=tuple((x,y,z) for x,y,z in grid if y<rows[0][x] and z<rows[1][x] and z<rows[2][y] and not(x>=2 and y>=1 and z>=1))
  if any(sum(p)>R for p in T):continue
  yield rows,T

def key(rows):return tuple(tuple(row) for row in rows)

raw=json.loads((HERE/'low_height_weighted_certificates.json').read_text())
certs={key(c['rows']):c for c in raw}
assert len(certs)==len(raw)
count4=0;max4=0
for rows,T in shapes(4):count4+=1;max4=max(max4,len(T))
assert (count4,max4)==(3928,29)
count5=0;max5=0;replayed=0;minmargin=None
for rows,T in shapes(5):
 count5+=1;m=len(T);max5=max(max5,m)
 if m<30:continue
 c=certs.pop(rows);assert c['m']==m
 sums=tuple(sum(p[i] for p in T) for i in range(3));assert list(sums)==c['sums']
 ts=set(T);total=Fraction(0);coeff=[Fraction(0)]*3
 for item in c['dual']:
  p=tuple(item['point']);y=Fraction(item['coefficient']);assert p in ts and y>=0
  total+=y
  for i in range(3):coeff[i]-=y*p[i]
 assert total==3*m
 beta=list(map(Fraction,c['beta']));assert all(b>=0 for b in beta)
 for i in range(3):assert coeff[i]+beta[i]==-4*sums[i]
 bound=sum(beta);assert bound==Fraction(c['lower_bound']) and bound>=m-1
 margin=bound-(m-1);minmargin=margin if minmargin is None else min(minmargin,margin)
 replayed+=1
assert not certs and count5==70175 and max5==43
print(json.dumps(dict(status='independent exact coverage and dual replay passed',degree4_shapes=count4,degree4_max_cardinality=max4,degree5_shapes=count5,degree5_max_cardinality=max5,exact_duals_replayed=replayed,minimum_margin=str(minmargin)),indent=2))
